version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    # volumes:
      # - mysql_data:/var/lib/mysql
    # networks:
      # - mysql_network
  adminer: 
    image: adminer:latest
    ports:
      - "8080:8080"
# volumes:
#   mysql_data:

# networks:
#   mysql_network:
#     driver: bridge
